// src/stateValues.js

const stateValues = {
    alabama: 6,
    alaska: 6,
    arizona: 3,
    arkansas: 6,
    california: 0,
    colorado: 2,
    connecticut: 0,
    delaware: 0,
    florida: 4,
    georgia: 4,
    hawaii: 0,
    idaho: 6,
    illinois: 0,
    indiana: 5,
    iowa: 4,
    kansas: 6,
    kentucky: 6,
    louisiana: 6,
    maine: 1,
    maryland: 0,
    massachusetts: 0,
    michigan: 2,
    minnesota: 1,
    mississippi: 6,
    missouri: 5,
    montana: 6,
    nebraska: 6,
    nevada: 3,
    new_hampshire: 3,
    new_jersey: 0,
    new_mexico: 2,
    new_york: 0,
    north_carolina: 3,
    north_dakota: 6,
    ohio: 4,
    oklahoma: 6,
    oregon: 1,
    pennsylvania: 3,
    rhode_island: 0,
    south_carolina: 5,
    south_dakota: 6,
    tennessee: 6,
    texas: 5,
    utah: 6,
    vermont: 0,
    virginia: 2,
    washington: 1,
    west_virginia: 6,
    wisconsin: 3,
    wyoming: 6,
    dc: 0,
  };
  
  export default stateValues;
  